// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"example/pkg/api"
	"example/pkg/api/handler"
	"example/pkg/config"
	"example/pkg/db"
	"example/pkg/repository"
	"example/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg *config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserDataBase(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	adminRepository := repository.NewAdminRepository(gormDB)
	adminUseCase := usecase.NewAdminUseCase(adminRepository)
	adminHandler := handler.NewAdminHandler(adminUseCase)
	serverHTTP := http.NewServerHttp(userHandler, adminHandler)
	return serverHTTP, nil
}
